config/routes.rb
Rails.application.routes.draw do
  scope ":lang", :constraints => Iqvoc.routing_constraint do
    get "similar/new" => "similar_terms#new", as: 'new_similar'
    get "similar" => "similar_terms#create"
  end
end

app/controllers/similar_terms_controller.rb
# encoding: UTF-8

class SimilarTermsController < ApplicationController
  class InvalidParameterCombinationError < StandardError
    attr_reader :invalid_keys

    def initialize(*invalid_keys)
      @invalid_keys = invalid_keys
      super("The combination of parameters #{invalid_keys.join(', ')} is not allowed.")
    end
  end

  rescue_from InvalidParameterCombinationError, with: :handle_invalid_combination

  resource_description do
    name 'Similar concepts'
  end

  api :GET, ':lang/similar', <<-DOC
    Returns labels which are semantically (not orthographically) similar,
    as determined by concept relations.
  DOC
  formats [:html, :ttl, :rdf, :xml, :json]
  param :terms, String, :required => true, :desc => <<-DOC
    One or more terms (comma-separated, CSV-style) to be processed.
  DOC
  example <<-DOC
    GET /de/similar.ttl?terms=wald,baum

    # omitted namespace definitions
    query:top skos:altLabel "Dünenwald"@de;
              skos:altLabel "Baumart"@de.
  DOC

  def create
    authorize! :read, Iqvoc::Concept.base_class

    lang = params[:lang]
    options = {
      synonyms_only: (%w[1 true].include?(params[:synonyms_only]) or params[:mode] == 'synonyms_only'),
      related_only: (%w[1 true].include?(params[:related_only]) or params[:mode] == 'related_only')
    }

    if options[:synonyms_only] and options[:related_only]
      raise InvalidParameterCombinationError.new(:synonyms_only, :related_only)
    end

    @terms = InlineDataHelper.parse_inline_values(similar_terms_params)

    respond_to do |format|
      format.html do
        @results = Services::SimilarTermsService.ranked(lang, options, *@terms)
        render :show
      end
      format.any(:rdf, :ttl, :nt, :xml) do
        @results = Services::SimilarTermsService.alphabetical(lang, options, *@terms)
        render :show
      end
      format.json do
        results = Services::SimilarTermsService.alphabetical(lang, options, *@terms)
        render json: create_json_response(results.map { |c| c.value })
      end
    end

  rescue CSV::MalformedCSVError => e
    respond_to do |format|
      format.html do
        flash[:error] = I18n.t('txt.controllers.similar_terms.parsing_error')
        redirect_to new_similar_url
      end
      format.any(:rdf, :ttl, :nt, :xml) do
        @terms = []
        @results = []
        render :show
      end
      format.json do
        render json: create_json_response([])
      end
    end
  end

  def new
  end

  private

  def create_json_response(results)
    {
      "url": request.original_url,
      "total_results": results.length,
      "results": results
    }.to_json
  end

  def handle_invalid_combination(exception)
    render_error(exception.message, :bad_request)
  end

  def render_error(message, status)
    respond_to do |format|
      format.any(:rdf, :ttl, :nt, :xml) { head status}

      format.json { render json: { message: message }, status: status }
    end
  end

  def similar_terms_params
    params.require(:terms)
  end
end

app/views/similar_terms/_form.html.erb
<%= bootstrap_form_tag(url: similar_url, method: :get) do |f| %>
  <div class="p-3 row no-gutters align-items-center bg-white">
    <div class="col-auto">
      <i class="fa fa-search fa-lg"></i>
    </div>
    <div class="col">
      <%= f.text_field :terms, hide_label: true, autofocus: (@terms ? false : true), wrapper_class: 'mb-0',
                       class: 'form-control-lg form-control-borderless border-0', autocomplete: 'off',
                       required: true,
                       value: (@terms ? InlineDataHelper.generate_inline_values(@terms) : params[:terms])
      %>
    </div>
    <div class="col-auto">
      <%= f.submit t('txt.views.search_results.submit'), class: 'btn btn-block btn-lg btn-primary p-2' %>
    </div>
  </div>
  <div class="py-3 row">
    <div class="col-auto">
      <%= f.radio_button :mode, :all, label: "Alle", inline: true, checked: (params[:mode] == 'all' or params[:mode].blank? ) %>
      <%= f.radio_button :mode, :synonyms_only, label: t('txt.views.similar_terms.synonyms_only'), inline: true, checked: params[:mode] == 'synonyms_only' %>
      <%= f.radio_button :mode, :related_only, label: t('txt.views.similar_terms.related_only'), inline: true, checked: params[:mode] == 'related_only' %>
    </div>
  </div>
<% end %>

app/views/similar_terms/new.html.erb
<div class="text-center my-5">
  <h1 class="mb-5">
    <%= t("txt.views.similar_terms.title") %>
  </h1>

  <div class="row justify-content-center">
    <div class="col-12 col-md-10 col-lg-8">
      <%= render 'form' %>
    </div>
  </div>
</div>

<div class="my-5">
  <h2 class="text-center my-4">
    <%= t("txt.views.similar_terms.about.title") %>
  </h2>

  <div class="row col-md-8 offset-md-2">
    <%= simple_format t("txt.views.similar_terms.about.description") %>
  </div>
</div>

app/views/similar_terms/show.html.erb
<% if @results.any? %>
  <h2 class="text-center my-5">
    <%= raw t('txt.views.similar_terms.results', terms: @terms.join(', '), count: @results.size) %>
  </h2>

  <ol>
    <% (@results || []).each do |data|
      label = data[0]
      concepts = data[1..-1]
    %>
      <li>
        <%= label.value %>
        (<%= concepts.map do |concept|
        origin = concept.origin
        link_to origin, rdf_url(origin, :format => nil, :lang => nil)
      end.join(", ").html_safe %>)
      </li>
    <% end %>
  </ol>
<% else %>
  <h2 class="text-center my-5">
    <%= t('txt.views.similar_terms.no_results') %>
  </h2>
<% end %>

<div class="text-center my-5">
  <h1 class="mb-5">
    <%= t("txt.views.similar_terms.title") %>
  </h1>

  <div class="row justify-content-center">
    <div class="col-12 col-md-10 col-lg-8">
      <%= render 'form' %>
    </div>
  </div>
</div>